# Generated by Django 5.2.8 on 2025-11-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='text',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
